# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgscore.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 441)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 471, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.L1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.L1.setFont(font)
        self.L1.setObjectName("L1")
        self.horizontalLayout.addWidget(self.L1)
        self.C1 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.C1.setObjectName("C1")
        import sqlite3
        conn = sqlite3.connect('MyCricket.db')
        self.horizontalLayout.addWidget(self.C1)
        sql="select name from teams"
        cur=conn.execute(sql)
        teams=[]
        for row in cur:
            self.C1.addItem(row[0])        
        conn.close()
        self.L2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.L2.setFont(font)
        self.L2.setObjectName("L2")
        self.horizontalLayout.addWidget(self.L2)
        self.C2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.C2.setObjectName("C2")
        self.C2.addItem("")
        self.C2.addItem("")
        self.C2.addItem("")
        self.C2.addItem("")
        self.C2.addItem("")
        self.horizontalLayout.addWidget(self.C2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 120, 481, 251))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout_2.addWidget(self.listWidget_2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 100, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(350, 100, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 380, 481, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.calculate)
        self.horizontalLayout_3.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)

        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def calculate(self):
        import sqlite3
        conn = sqlite3.connect('MyCricket.db')
        team=self.C1.currentText()
        self.listWidget.clear()
        sql1="select players, value from teams where name='"+team+"'"
        cur=conn.execute(sql1)
        row=cur.fetchone()
        #print (row[0])
        selected=row[0].split(',')
        #print (selected)
        self.listWidget.addItems(selected)
        teamttl=0
        #print("ded")
        self.listWidget_2.clear()
        match=self.C2.currentText()
        for i in range(self.listWidget.count()):
            ttl, batscore, bowlscore, fieldscore=0,0,0,0
            nm=self.listWidget.item(i).text()
            cursor=conn.execute("select * from "+match+" where player='"+nm+"'")
            row=cursor.fetchone()
            #print ("fekn")
            #print(row)
            batscore=int(row[1]/2)
            if batscore>=50: batscore+=5
            if batscore>=100: batscore+=10
            if row[1]>0:
                sr=row[1]/row[2]
                if sr>=80 and sr<100: batscore+=2
                if sr>=100:batscore+=4
            batscore=batscore+row[3]
            batscore=batscore+2*row[4]
            #print ("batting score=", batscore)
            bowlscore=row[8]*10
            if row[8]>=3: bowlscore=bowlscore+5
            if row[8]>=5: bowlscore=bowlscore=bowlscore+10
            if row[7]>0:
                er=6*row[7]/row[5]
                #print ("eco:")
                if er<=2: bowlscore=bowlscore+10
                if er>2 and er<=3.5: bowlscore=bowlscore+7
                if er>3.5 and er<=4.5: bowlscore=bowlscore+4
            fieldscore=(row[9]+row[10]+row[11])*10            
            ttl=batscore+bowlscore+fieldscore
            #print("frfm")
            self.listWidget_2.addItem(str(ttl))
            #print("rb")
            teamttl=teamttl+ttl
            #int(teamttl)
            
            #self.scorelabel.setText(str(teamttl))
        #print("gt")
        self.lineEdit.setText(str(teamttl))
        #print("du")
    
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.L1.setText(_translate("Dialog", "Choose Team"))
        self.L2.setText(_translate("Dialog", "Choose Match"))
        self.C2.setItemText(0, _translate("Dialog", "Match1"))
        self.C2.setItemText(1, _translate("Dialog", "Match2"))
        self.C2.setItemText(2, _translate("Dialog", "Match3"))
        self.C2.setItemText(3, _translate("Dialog", "Match4"))
        self.C2.setItemText(4, _translate("Dialog", "Match5"))
        self.label.setText(_translate("Dialog", "Players"))
        self.label_2.setText(_translate("Dialog", "score"))
        self.pushButton.setText(_translate("Dialog", "Calculate Score"))

        #self.lineEdit.setText(_translate("Dialog", "00"))
        self.lineEdit.setText(_translate("Dialog", "00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
